### ISSUE TITLE
What's the difference between <-- and <== in circom?

### ISSUE THREAD

**Issue by 1k2222** [kaleido-io/kaleido-iden3-samples#15]
Hi, this is Ling Zhang from Weiming's team. I'm confused about the opeartor <-- and <== in circom. 

For example. If I wrote **c <== a * b**, the value of **c** is always be equal to **a * b** since singals are immutable. In my opinion, add a constraint c === a * b is redundant. So why we should use “<==” ？

**Comment by Chengxuan** [comment]
@1k2222 Hi Ling, that's a good question. Here is an explanation I found: https://docs.circom.io/circom-language/constraint-generation/  As per my understanding it's useful when `a` `b` are variables and avoid assignment mistakes. 

Circom has a github repo: https://github.com/iden3/circom, you might be able to find more there.
