### ISSUE TITLE
Regression in publishing issued claim

### ISSUE THREAD

**Issue by nedgar** [kaleido-io/kaleido-iden3-samples#28]
Steps:
- `make clean identities`
- deploy contracts
- publish genesis state on-chain
- `make issue-claim`
- publish new state on-chain

This fails using the latest from main branch.

**Comment by Chengxuan** [comment]
This is a result of https://github.com/kaleido-io/kaleido-iden3-samples/pull/24. @nedgar you raised a PR to fix the readme for this: https://github.com/kaleido-io/kaleido-iden3-samples/pull/26/files

**Comment by nedgar** [comment]
Shouldn't it still be possible to issue and publish claims, though, even if publishing is not required?

**Comment by Chengxuan** [comment]
@nedgar I assumed that you failed to publish the new state as in the `stateTransition_inputs.json` file the `oldUserState` and `newUserState` are identical. If you saw something different, please let me know.

I raised a PR to handle that case better: https://github.com/kaleido-io/kaleido-iden3-samples/pull/31

I didn't want to remove the code that generates the `stateTransition_inputs.json` as we might need that if we ever want zkp back.


FYI @jimthematrix

**Comment by nedgar** [comment]
@Chengxuan yes, that's the case. I ran `make issue-claim` twice.

**Comment by nedgar** [comment]
Actually, let me re-check with the reported steps.

**Comment by Chengxuan** [comment]
In https://github.com/kaleido-io/kaleido-iden3-samples/pull/36 I've removed the generation of the state transition file when a claim is issued via signature as it's confusing.

Feel free to reopen this issue if you have more questions
